name: CI - Pytest and Flake8

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code in the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python with the specified version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.*' 

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run flake8 for style checks
      - name: Run flake8
        run: |
          pip install flake8
          flake8 .

      # Run pytest for unit tests
      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings
